/**
 * @eudi-verify/server - Verifier Engine Interface
 *
 * Abstraction over the underlying EUDI verification protocol implementation.
 * Enables swapping between:
 * - OpenEUDI (primary, Luxembourg-based Apache-2.0 library)
 * - Sphereon OID4VC (fallback, mitigates OpenEUDI single-contributor risk)
 * - MockEngine (testing and demo without external dependencies)
 *
 * The engine handles OpenID4VP protocol details; the server handles:
 * - HTTP routing and validation
 * - Token minting and verification
 * - Session storage
 * - Rate limiting
 */

import type {
  Session,
  VerificationRequest,
  VerifiedClaims,
  SessionStatus,
  VerifierMode,
} from "./types.js";

/**
 * Configuration for creating a verification session.
 */
export interface CreateSessionConfig {
  /** Unique session ID (generated by server) */
  sessionId: string;
  /** Claims to request from the wallet */
  request: VerificationRequest;
  /** Base URL for callback endpoints (e.g., https://example.com/api/eudi) */
  baseUrl: string;
  /** Session TTL in milliseconds */
  ttlMs: number;
}

/**
 * Result of session creation from the engine.
 */
export interface CreateSessionResult {
  /** URL for the QR code (OpenID4VP authorization request) */
  qrUrl: string;
  /** Engine-specific data to store with session (e.g., nonce, keys) */
  engineData?: unknown;
}

/**
 * Callback data received from the wallet.
 */
export interface CallbackData {
  /** Session ID extracted from the callback */
  sessionId: string;
  /** Raw response from wallet (VP token or encrypted JWE) */
  response: string;
}

/**
 * Result of processing a wallet callback.
 */
export interface CallbackResult {
  /** Whether verification succeeded */
  success: boolean;
  /** Verified claims (if success) */
  claims?: VerifiedClaims;
  /** Error message (if !success) */
  error?: string;
  /** New status for the session */
  status: SessionStatus;
}

/**
 * Verifier engine interface — the protocol abstraction layer.
 *
 * Implementations handle OpenID4VP specifics:
 * - Generating authorization requests (QR URLs)
 * - Verifying VP responses (signatures, trust lists, disclosure)
 * - Managing cryptographic material (nonces, keys)
 *
 * The server layer handles everything else:
 * - Session lifecycle and storage
 * - Token minting (captcha pattern)
 * - HTTP request/response handling
 * - Rate limiting and security checks
 *
 * @example
 * ```ts
 * // Using OpenEUDI engine (production)
 * import { OpenEudiEngine } from './engines/openeudi.js';
 * const engine = new OpenEudiEngine({ mode: 'demo' });
 *
 * // Using mock engine (testing)
 * import { MockEngine } from './engines/mock.js';
 * const engine = new MockEngine();
 * ```
 */
export interface VerifierEngine {
  /**
   * Engine identifier for logging and debugging.
   */
  readonly name: string;

  /**
   * Operating mode (demo returns simulated credentials).
   */
  readonly mode: VerifierMode;

  /**
   * Create a new verification session.
   *
   * Generates the OpenID4VP authorization request URL that will be
   * encoded in the QR code for wallet scanning.
   *
   * @param config - Session configuration
   * @returns QR URL and optional engine-specific data to persist
   * @throws If session creation fails
   */
  createSession(config: CreateSessionConfig): Promise<CreateSessionResult>;

  /**
   * Parse and validate a wallet callback.
   *
   * Called when the wallet POSTs to the callback endpoint.
   * Extracts session ID and validates the response format.
   *
   * @param rawBody - Raw request body (form-encoded or JSON)
   * @returns Parsed callback data
   * @throws If callback is malformed
   */
  parseCallback(rawBody: string): Promise<CallbackData>;

  /**
   * Process a wallet callback and verify the presentation.
   *
   * Performs cryptographic verification:
   * - VP signature validation
   * - Trust list verification (production)
   * - Selective disclosure validation
   * - Nonce/state binding checks
   *
   * @param data - Parsed callback data
   * @param session - Current session (with engineData)
   * @returns Verification result with claims or error
   */
  handleCallback(data: CallbackData, session: Session): Promise<CallbackResult>;

  /**
   * Generate the authorization request object for PAR.
   *
   * Called when wallet fetches the request_uri.
   * Returns a signed JWT containing the OpenID4VP request.
   *
   * @param session - Session to generate request for
   * @returns Signed authorization request JWT
   */
  getAuthorizationRequest?(session: Session): Promise<string>;

  /**
   * Clean up any resources associated with a cancelled session.
   *
   * Optional — implement if the engine maintains state that needs cleanup.
   *
   * @param session - Session being cancelled
   */
  cancelSession?(session: Session): Promise<void>;

  /**
   * Initialize the engine (load keys, connect to services, etc.).
   *
   * Called once during server startup.
   */
  initialize?(): Promise<void>;

  /**
   * Shutdown the engine gracefully.
   *
   * Called during server shutdown.
   */
  shutdown?(): Promise<void>;
}

/**
 * Configuration for MockEngine.
 */
export interface MockEngineConfig {
  /**
   * Simulated delay before verification completes (ms).
   * @default 1000
   */
  verificationDelayMs?: number;

  /**
   * Probability that verification succeeds (0-1).
   * @default 1.0
   */
  successRate?: number;

  /**
   * Default claims to return for all verifications.
   */
  defaultClaims?: VerifiedClaims;
}

/**
 * Mock engine for testing and demos without external dependencies.
 *
 * Simulates the verification flow with configurable behavior:
 * - Immediate or delayed verification
 * - Configurable success/failure rates
 * - Custom claim responses
 *
 * WARNING: This engine does NOT perform real verification.
 * Never use in production — it accepts any input as valid.
 *
 * @example
 * ```ts
 * const engine = new MockEngine({
 *   verificationDelayMs: 2000, // Simulate wallet interaction time
 *   successRate: 0.9, // 90% success rate
 *   defaultClaims: { age_over_18: true },
 * });
 * ```
 */
export class MockEngine implements VerifierEngine {
  readonly name = "mock";
  readonly mode: VerifierMode = "demo";

  private config: Required<MockEngineConfig>;

  constructor(config: MockEngineConfig = {}) {
    this.config = {
      verificationDelayMs: config.verificationDelayMs ?? 1000,
      successRate: config.successRate ?? 1.0,
      defaultClaims: config.defaultClaims ?? {},
    };
  }

  async createSession(
    config: CreateSessionConfig,
  ): Promise<CreateSessionResult> {
    const requestedClaims = Object.keys(config.request).filter(
      (k) => config.request[k] === true,
    );

    const qrUrl = this.buildMockQrUrl(
      config.sessionId,
      config.baseUrl,
      requestedClaims,
    );

    return {
      qrUrl,
      engineData: {
        requestedClaims,
        createdAt: Date.now(),
      },
    };
  }

  async parseCallback(rawBody: string): Promise<CallbackData> {
    const params = new URLSearchParams(rawBody);
    const response = params.get("response");
    const sessionId = params.get("session_id") || params.get("state");

    if (!response || !sessionId) {
      throw new Error("Invalid callback: missing response or session_id");
    }

    return { sessionId, response };
  }

  async handleCallback(
    data: CallbackData,
    session: Session,
  ): Promise<CallbackResult> {
    if (this.config.verificationDelayMs > 0) {
      await this.delay(this.config.verificationDelayMs);
    }

    const shouldSucceed = Math.random() < this.config.successRate;

    if (!shouldSucceed) {
      return {
        success: false,
        error: "Simulated verification failure",
        status: "rejected",
      };
    }

    const claims = this.generateMockClaims(session.request);

    return {
      success: true,
      claims,
      status: "verified",
    };
  }

  async getAuthorizationRequest(session: Session): Promise<string> {
    return JSON.stringify({
      type: "mock_authorization_request",
      sessionId: session.id,
      request: session.request,
    });
  }

  async cancelSession(_session: Session): Promise<void> {
    // No cleanup needed for mock engine
  }

  private buildMockQrUrl(
    sessionId: string,
    baseUrl: string,
    claims: string[],
  ): string {
    const params = new URLSearchParams({
      session_id: sessionId,
      claims: claims.join(","),
      mock: "true",
    });

    return `${baseUrl}/mock-wallet?${params.toString()}`;
  }

  private generateMockClaims(request: VerificationRequest): VerifiedClaims {
    const claims: VerifiedClaims = { ...this.config.defaultClaims };

    if (request.age_over_18) claims.age_over_18 = true;
    if (request.age_over_21) claims.age_over_21 = true;
    if (request.nationality) claims.nationality = "LU";
    if (request.given_name) claims.given_name = "Max";
    if (request.family_name) claims.family_name = "Mustermann";
    if (request.birth_date) claims.birth_date = "1990-01-15";

    return claims;
  }

  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}

/**
 * Placeholder for OpenEUDI engine implementation.
 *
 * Will wrap @openeudi/core and @openeudi/openid4vp to provide:
 * - Real OpenID4VP authorization requests
 * - Demo mode with simulated wallet responses
 * - Production mode with full crypto verification
 *
 * Implementation deferred to WP2.
 */
export interface OpenEudiEngineConfig {
  /** Operating mode */
  mode: VerifierMode;
  /** Base URL for callback endpoints */
  baseUrl: string;
  /** Custom session TTL (ms) */
  sessionTtlMs?: number;
}

/**
 * Placeholder for Sphereon OID4VC engine implementation.
 *
 * Fallback engine using Sphereon's OID4VC libraries.
 * Mitigates OpenEUDI's single-contributor bus factor risk.
 *
 * Implementation deferred until OpenEUDI proves unstable.
 */
export interface SphereonEngineConfig {
  mode: VerifierMode;
  baseUrl: string;
}
