#!/usr/bin/env bash
# Generate nginx real_ip trust list for Bunny CDN edge servers.
# See docs/deploy-cdn-examples.md#bunnynet. Re-run periodically (edge IPs change).
set -euo pipefail

OUT="${1:-/etc/nginx/conf.d/bunny-real-ip.conf}"
TMP="$(mktemp)"

cleanup() {
  rm -f "$TMP"
}
trap cleanup EXIT

curl -fsSL "https://bunnycdn.com/api/system/edgeserverlist" -o "$TMP"

{
  echo "# Generated by scripts/install-bunny-real-ip.sh — do not edit by hand"
  echo "real_ip_header X-Forwarded-For;"
  echo "real_ip_recursive on;"
  python3 - "$TMP" <<'PY'
import sys
import xml.etree.ElementTree as ET

ns = {"i": "http://www.w3.org/2001/XMLSchema-instance"}
root = ET.parse(sys.argv[1]).getroot()
for ip in root.findall(".//{*}string"):
    value = (ip.text or "").strip()
    if value:
        print(f"set_real_ip_from {value};")
PY
} | sudo tee "$OUT" > /dev/null

sudo nginx -t
sudo systemctl reload nginx
echo "Installed Bunny real_ip config at $OUT"
